- name: Restart Tomcat Windows Service
  hosts: windows
  tasks:
    - name: Stop Tomcat9 service
      win_service:
        name: Apache Tomcat 9.0 Tomcat9
        state: stopped
    - name: Start Tomcat9 service
      win_service:
        name: Apache Tomcat 9.0 Tomcat9
        state: started