- name: Restart Tomcat service on Windows
  hosts: windows
  gather_facts: no

  tasks:
    - name: Stop Tomcat service
      win_service:
        name: Tomcat9
        state: stopped

    - name: Start Tomcat service
      win_service:
        name: Tomcat9
        state: started
