- name: Restart Tomcat
  hosts: windows
  tasks:
    - name: Stop Tomcat
      win_shell: 'C:\Tomcat9\apache-tomcat-9.0.107\bin\shutdown.bat'

    - name: Wait for 5 seconds
      win_wait_for:
        timeout: 5

    - name: Start Tomcat
      win_shell: 'C:\Tomcat9\apache-tomcat-9.0.107\bin\startup.bat'
